# Generated by Django 6.0.4 on 2026-07-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('coordenador', 'Coordenador Bebelingue'), ('diretor', 'Diretor de Escola'), ('professor', 'Professor')], default='professor', max_length=20),
        ),
    ]
