# Generated by Django 6.0.4 on 2026-07-23 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ia_provider', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)')], default='anthropic', help_text='Provedor de IA para o chat', max_length=20)),
                ('ia_modelo', models.CharField(default='claude-sonnet-4-20250514', help_text='Ex: claude-sonnet-4-20250514, gpt-4o', max_length=100)),
                ('ia_api_key', models.CharField(default='', help_text='API key do provedor de IA', max_length=255)),
                ('tts_provider', models.CharField(choices=[('elevenlabs', 'ElevenLabs'), ('openai_tts', 'OpenAI TTS')], default='elevenlabs', max_length=20)),
                ('tts_api_key', models.CharField(default='', help_text='API key do provedor de TTS', max_length=255)),
                ('tts_voice_id', models.CharField(blank=True, default='', help_text='ElevenLabs voice_id. Ex: 21m00Tcm4TlvDq8ikWAM', max_length=100)),
                ('tts_modelo', models.CharField(blank=True, default='eleven_multilingual_v2', help_text='ElevenLabs model_id (ex: eleven_multilingual_v2) ou voz do OpenAI TTS (ex: alloy, nova).', max_length=100)),
                ('stt_provider', models.CharField(choices=[('openai_whisper', 'OpenAI Whisper'), ('google_stt', 'Google Speech-to-Text')], default='openai_whisper', max_length=20)),
                ('stt_api_key', models.CharField(default='', help_text='API key do provedor de STT', max_length=255)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diretor', to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diretores', to='escolas.escola')),
            ],
            options={
                'verbose_name': 'Diretor',
                'verbose_name_plural': 'Diretores',
            },
        ),
        migrations.AddField(
            model_name='escola',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escolas', to='escolas.plano'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='escolas.escola')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year do currículo (1 a 5). Define qual TG a turma segue.')),
                ('nome', models.CharField(help_text='Ex: A, B, "Tarde"', max_length=20)),
                ('qtd_alunos', models.PositiveIntegerField(default=0, help_text='Quantos alunos a turma tem. Substitui o cadastro individual.')),
                ('aulas_por_semana', models.PositiveIntegerField(choices=[(3, '3x por semana'), (4, '4x por semana'), (5, '5x por semana')], default=3, help_text='Frequência contratada pela escola. O TG de 4x é o de 3x mais uma Communication Class; o de 5x, mais outra.')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='escolas.escola')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='escolas.professor')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'unique_together': {('escola', 'year', 'nome')},
            },
        ),
    ]
