# Generated by Django 6.0.4 on 2026-07-30 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0003_alter_aula_codigo_alter_aula_frequencia_minima_and_more'),
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='aulas_por_semana',
            field=models.PositiveIntegerField(default=3, help_text='Depreciado — a frequência vem do TG da série.'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='year',
            field=models.IntegerField(help_text='Year do currículo (1 a 9). Herda o da série.'),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome que a escola dá ao segmento. Ex: "Fundamental", "K2".', max_length=60)),
                ('year', models.PositiveIntegerField(help_text='Year do currículo (1 a 9) que esta série cursa.')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='escolas.escola')),
                ('tg', models.ForeignKey(blank=True, help_text='Cronograma que esta série segue. O coordenador Bebelingue escolhe. Vazio = ainda não vinculado (as turmas não têm currículo até então).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series', to='curriculo.tg')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
                'ordering': ['escola', 'year', 'nome'],
                'unique_together': {('escola', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='turma',
            name='serie',
            field=models.ForeignKey(help_text='A série a que esta turma pertence — define o TG que ela segue.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='escolas.serie'),
        ),
    ]
