# Generated by Django 6.0.4 on 2026-04-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='modelo_ia',
        ),
        migrations.AddField(
            model_name='plano',
            name='ia_api_key',
            field=models.CharField(default='', help_text='API key do provedor de IA', max_length=255),
        ),
        migrations.AddField(
            model_name='plano',
            name='ia_modelo',
            field=models.CharField(default='claude-sonnet-4-20250514', help_text='Ex: claude-sonnet-4-20250514, gpt-4o', max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='ia_provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)')], default='anthropic', help_text='Provedor de IA para o chat', max_length=20),
        ),
        migrations.AddField(
            model_name='plano',
            name='stt_api_key',
            field=models.CharField(default='', help_text='API key do provedor de STT', max_length=255),
        ),
        migrations.AddField(
            model_name='plano',
            name='stt_provider',
            field=models.CharField(choices=[('openai_whisper', 'OpenAI Whisper'), ('google_stt', 'Google Speech-to-Text')], default='openai_whisper', max_length=20),
        ),
        migrations.AlterField(
            model_name='plano',
            name='tts_api_key',
            field=models.CharField(default='', help_text='API key do provedor de TTS', max_length=255),
        ),
        migrations.AlterField(
            model_name='plano',
            name='tts_provider',
            field=models.CharField(choices=[('elevenlabs', 'ElevenLabs'), ('openai_tts', 'OpenAI TTS')], default='elevenlabs', max_length=20),
        ),
    ]
