# Generated by Django 6.0.4 on 2026-04-07 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0002_remove_plano_modelo_ia_plano_ia_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diretores', to='escolas.escola')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diretor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diretor',
                'verbose_name_plural': 'Diretores',
            },
        ),
    ]
