# Generated by Django 6.0.4 on 2026-07-30 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_dados_serie_tg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='aulas_por_semana',
        ),
    ]
