# Generated by Django 6.0.4 on 2026-04-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_diretor'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='tts_modelo',
            field=models.CharField(blank=True, default='eleven_multilingual_v2', help_text='ElevenLabs model_id (ex: eleven_multilingual_v2) ou voz do OpenAI TTS (ex: alloy, nova).', max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='tts_voice_id',
            field=models.CharField(blank=True, default='', help_text='ElevenLabs voice_id. Ex: 21m00Tcm4TlvDq8ikWAM', max_length=100),
        ),
    ]
