# Generated by Django 6.0.4 on 2026-09-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0004_remove_turma_aulas_por_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='ia_effort',
            field=models.CharField(blank=True, choices=[('none', 'none — sem raciocínio'), ('low', 'low'), ('medium', 'medium (padrão)'), ('high', 'high'), ('xhigh', 'xhigh'), ('max', 'max — mais lento e mais caro')], default='medium', help_text='Esforço de raciocínio, para modelos que suportam (ex: gpt-5.6-terra). Vazio = não envia o parâmetro. Ignorado pelo Anthropic, que não expõe esse controle.', max_length=10),
        ),
    ]
