# Generated by Django 6.0.4 on 2026-07-23 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('jogo', 'Jogo'), ('tecnica', 'Técnica'), ('rotina', 'Rotina'), ('recurso', 'Recurso / Material')], help_text='Jogo (Simon Says) · Técnica (Sandwich) · Rotina (BeCalendar) · Recurso (livro, áudio)', max_length=20)),
                ('nome', models.CharField(help_text='Nome exato como aparece no TG. Ex: "Simon Says", "BeCalendar"', max_length=200)),
                ('descricao', models.TextField(blank=True, default='', help_text='O que é esta atividade, em uma ou duas frases.')),
                ('como_conduzir', models.TextField(blank=True, default='', help_text='Passo a passo de como conduzir. ESTE CAMPO VAI PARA O KEVIN — sem ele o Kevin improvisa a atividade. Fonte oficial: seção "Games Bank", no início do TG.')),
                ('objetivo_pedagogico', models.TextField(blank=True, default='', help_text='O que se pratica. Ex: "vocabulário de rotina diária".')),
                ('materiais', models.CharField(blank=True, default='', help_text='Ex: flashcards, bola, quadro. Vazio se não precisa de nada.', max_length=300)),
                ('duracao_estimada', models.PositiveIntegerField(blank=True, help_text='Duração em minutos (opcional).', null=True)),
                ('arquivo_url', models.URLField(blank=True, default='', help_text='Só para Recurso: link do livro, áudio ou vídeo.')),
                ('tags', models.CharField(blank=True, default='', help_text='Palavras-chave separadas por vírgula, para a busca. Ex: "fruits, vocabulary, movement"', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_criadas', to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(blank=True, help_text='VAZIO = catálogo oficial da Bebelingue (todas as escolas veem). Preenchido = atividade local, visível só nessa escola.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='escolas.escola')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades (catálogo)',
                'ordering': ['tipo', 'nome'],
                'unique_together': {('nome', 'escola')},
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, help_text='Gerado automaticamente. Ex: Y5-MAR-W1C1', max_length=30, unique=True)),
                ('year', models.PositiveIntegerField(help_text='Year do currículo: 1 a 5.')),
                ('mes', models.PositiveIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], help_text='Mês do TG. O TG é organizado por mês, não por Unit.')),
                ('semana', models.PositiveIntegerField(default=1, help_text='Semana dentro do mês: 1 a 5.')),
                ('numero_aula', models.PositiveIntegerField(default=1, help_text='Qual aula da semana: 1, 2, 3… (CLASS 1, CLASS 2 no TG)')),
                ('tipo', models.CharField(choices=[('content', 'Content Class'), ('communication', 'Communication Class'), ('culture', 'Culture Class'), ('extra', 'Extra Class / Festival')], default='content', help_text='Define o formato do roteiro e o que o Kevin espera da aula.', max_length=20)),
                ('frequencia_minima', models.PositiveIntegerField(default=3, help_text='Aparece para turmas com esta frequência semanal OU MAIOR. Use 3 para as aulas do TG base; 4 ou 5 para as Communication Classes extras dos TGs de 4x e 5x.')),
                ('unit', models.PositiveIntegerField(blank=True, help_text='Unit do material. Agrupa avaliação — NÃO é o eixo de navegação.', null=True)),
                ('lesson', models.CharField(blank=True, default='', help_text='Referência da lição no livro. Ex: "U1L1", "U1 L6 & L7"', max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('observacao', models.TextField(blank=True, default='', help_text='Aviso para o professor. Ex: "Convidar os alunos a vestir verde".')),
                ('kickoff', models.CharField(blank=True, default='', help_text='Mensagem que abre a aula quando o professor clica em "Iniciar aula". Vazio = usa o texto padrão do tipo de aula.', max_length=300)),
                ('background', models.CharField(choices=[('floresta', 'Floresta'), ('quarto', 'Quarto'), ('banheiro', 'Banheiro'), ('escola-int', 'Escola (interior)'), ('escola-ext', 'Escola (exterior)'), ('hospital', 'Hospital (exterior)'), ('hospital-int', 'Hospital (interior)')], default='floresta', help_text='Cenário de fundo do Kevin. Escolha o que combina com o vocabulário da aula.', max_length=30)),
            ],
            options={
                'verbose_name': 'Aula (TG)',
                'verbose_name_plural': 'Aulas (TG)',
                'ordering': ['year', 'mes', 'semana', 'numero_aula'],
                'unique_together': {('year', 'mes', 'semana', 'numero_aula')},
            },
        ),
        migrations.CreateModel(
            name='BlocoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('warm_up', 'Warm Up'), ('development', 'Development'), ('closure', 'Closure')], help_text='Em qual momento da aula este bloco acontece.', max_length=20)),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Posição dentro da fase: 1, 2, 3…')),
                ('titulo', models.CharField(blank=True, default='', help_text='Use quando não houver atividade no catálogo.', max_length=200)),
                ('instrucoes', models.TextField(blank=True, default='', help_text='Passos específicos DESTA aula, um por linha.')),
                ('referencia', models.CharField(blank=True, default='', help_text='Material e páginas. Ex: "Student\'s Book U1L1 (P. 10-11)"', max_length=200)),
                ('atividade', models.ForeignKey(blank=True, help_text='Atividade do catálogo (ex: "Simon Says"). Preencha sempre que existir — é o que permite o Kevin conduzir a atividade.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blocos', to='curriculo.atividade')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='curriculo.aula')),
            ],
            options={
                'verbose_name': 'Bloco da aula',
                'verbose_name_plural': 'Blocos da aula (roteiro)',
                'ordering': ['fase', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Como aparece no TG. Ex: "Integrated Activities - Unit 1 (exercises 1 and 2)"')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='curriculo.aula')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homeworks',
            },
        ),
        migrations.CreateModel(
            name='AulaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nao_iniciada', 'Não iniciada'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('pulada', 'Pulada')], default='nao_iniciada', max_length=20)),
                ('data_realizada', models.DateField(blank=True, help_text='Data real em que a aula foi dada. Preenchida automaticamente ao concluir.', null=True)),
                ('presentes', models.PositiveIntegerField(blank=True, help_text='Quantos alunos estavam presentes (opcional).', null=True)),
                ('observacoes', models.TextField(blank=True, default='', help_text='Anotação livre do professor sobre como foi a aula (opcional).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='curriculo.aula')),
                ('professor', models.ForeignKey(blank=True, help_text='Quem deu a aula (pode ser um substituto).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas_dadas', to='escolas.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_turma', to='escolas.turma')),
            ],
            options={
                'verbose_name': 'Aula da turma (execução)',
                'verbose_name_plural': 'Aulas das turmas (execução)',
                'ordering': ['-data_realizada', '-updated_at'],
                'unique_together': {('turma', 'aula')},
            },
        ),
    ]
