# Generated by Django 6.0.4 on 2026-04-07 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Ano do currículo')),
                ('ordem', models.IntegerField(help_text='Sequência dentro do ano')),
                ('titulo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['year', 'ordem'],
                'unique_together': {('year', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('musica', 'Música'), ('video', 'Vídeo'), ('texto', 'Texto'), ('audio', 'Áudio'), ('imagem', 'Imagem')], max_length=20)),
                ('arquivo_url', models.URLField(help_text='Link para o arquivo (S3, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='escolas.professor')),
            ],
            options={
                'verbose_name': 'Conteúdo',
                'verbose_name_plural': 'Conteúdos',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.TextField()),
                ('vocabulario', models.TextField(blank=True)),
                ('gramatica', models.TextField(blank=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='curriculo.aula')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homeworks',
            },
        ),
        migrations.CreateModel(
            name='AulaConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(help_text='Posição do conteúdo dentro da aula')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aula_conteudos', to='curriculo.aula')),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aula_conteudos', to='curriculo.conteudo')),
            ],
            options={
                'verbose_name': 'Conteúdo da Aula',
                'verbose_name_plural': 'Conteúdos da Aula',
                'ordering': ['ordem'],
                'unique_together': {('aula', 'conteudo')},
            },
        ),
        migrations.CreateModel(
            name='ProgressoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nao_iniciada', 'Não Iniciada'), ('parcial', 'Parcial'), ('concluida', 'Concluída')], default='nao_iniciada', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='curriculo.aula')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='escolas.turma')),
            ],
            options={
                'verbose_name': 'Progresso da Turma',
                'verbose_name_plural': 'Progressos das Turmas',
                'unique_together': {('turma', 'aula')},
            },
        ),
    ]
