# Generated by Django 6.0.4 on 2026-04-07 18:30

import apps.curriculo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='codigo',
            field=models.CharField(default=apps.curriculo.models.gerar_codigo_aula, help_text='Código único da aula (ex: UIS13DS)', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='descricao',
            field=models.TextField(default='', help_text='Descrição detalhada do que será discutido na aula'),
        ),
    ]
