# Generated by Django 6.0.4 on 2026-04-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_aula_codigo_aula_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='closure',
            field=models.TextField(blank=True, default='', help_text='Roteiro do CLOSURE (5-10 min) — enviado à IA como contexto.'),
        ),
        migrations.AddField(
            model_name='aula',
            name='development',
            field=models.TextField(blank=True, default='', help_text='Roteiro do DEVELOPMENT (30-40 min) — enviado à IA como contexto.'),
        ),
        migrations.AddField(
            model_name='aula',
            name='warm_up',
            field=models.TextField(blank=True, default='', help_text='Roteiro do WARM UP (10-15 min) — enviado à IA como contexto.'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='descricao',
            field=models.TextField(blank=True, default='', help_text='Descrição para exibição no app. NÃO é enviada à IA.'),
        ),
    ]
