# Generated by Django 6.0.4 on 2026-07-30 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_unit_como_chave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='codigo',
            field=models.CharField(editable=False, help_text='Gerado automaticamente. Ex: Y5-U1W1C1', max_length=30),
        ),
        migrations.AlterField(
            model_name='aula',
            name='frequencia_minima',
            field=models.PositiveIntegerField(default=3, help_text='Depreciado — a frequência vem do TG. Não usar.'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='year',
            field=models.PositiveIntegerField(help_text='Year do currículo: 1 a 9.'),
        ),
        migrations.CreateModel(
            name='TG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome que o coordenador lê ao escolher. Ex: "TG 3x — Year 5".', max_length=100)),
                ('year', models.PositiveIntegerField(help_text='Year a que este TG se aplica: 1 a 9.')),
                ('frequencia', models.IntegerField(choices=[(3, '3x por semana'), (4, '4x por semana'), (5, '5x por semana')], default=3, help_text='Aulas por semana deste cronograma (3, 4 ou 5).')),
                ('descricao', models.TextField(blank=True, default='', help_text='Anotação opcional sobre este TG.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TG (cronograma)',
                'verbose_name_plural': 'TGs (cronogramas)',
                'ordering': ['year', 'frequencia'],
                'unique_together': {('year', 'frequencia')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aula',
            name='tg',
            field=models.ForeignKey(help_text='O cronograma (3x/4x/5x) a que esta aula pertence.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='curriculo.tg'),
        ),
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together={('tg', 'unit', 'semana', 'numero_aula')},
        ),
    ]
