# Generated by Django 6.0.4 on 2026-07-30 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0003_alter_aula_codigo_alter_aula_frequencia_minima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='frequencia_minima',
        ),
    ]
