# Generated by Django 6.0.4 on 2026-04-07 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculo', '0001_initial'),
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(blank=True, help_text='Chat livre se nulo, chat contextual se preenchido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas', to='curriculo.aula')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='escolas.professor')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente')], max_length=10)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('audio', 'Áudio')], default='texto', max_length=10)),
                ('conteudo', models.TextField(help_text='Texto da mensagem ou URL do áudio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.conversa')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['created_at'],
            },
        ),
    ]
