# Generated by Django 4.2.30 on 2026-09-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='celebrar',
            field=models.BooleanField(default=False, help_text='A IA sinalizou (via tool-calling) que esta resposta celebra um acerto do Teacher/turma — dispara o modo "celebrate" do Kevin.'),
        ),
    ]
